/**
 * This file auto-generated by Fern from our API Definition.
 */

import { HappayApi } from "../../..";
import * as core from "../../../core";

export const AccountTypes: core.schemas.Schema<AccountTypes.Raw, HappayApi.AccountTypes> = core.schemas
  .string()
  .transform<HappayApi.AccountTypes>({
    parse: (value) => HappayApi.AccountTypes._parse(value),
    json: ({ value }) => value,
  });

export declare namespace AccountTypes {
  type Raw = string;
}
