/**
 * This file auto-generated by Fern from our API Definition.
 */

import { HappayApi } from "../../..";
import * as core from "../../../core";

export const CreateAccountResponse: core.schemas.ObjectSchema<
  CreateAccountResponse.Raw,
  HappayApi.CreateAccountResponse
> = core.schemas.object({
  accountId: core.schemas.property("account_id", core.schemas.string()),
  userId: core.schemas.property("user_id", core.schemas.string()),
});

export declare namespace CreateAccountResponse {
  interface Raw {
    account_id: string;
    user_id: string;
  }
}
