/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../environments";
import * as core from "../../../core";
import { HappayApi } from "../../..";
import urlJoin from "url-join";
import * as serializers from "../../../serialization";

export declare namespace Client {
  interface Options {
    environment?: environments.Environment | string;
    auth?: {
      token?: core.Supplier<core.BearerToken>;
    };
  }
}

/**
 * Accounts holds the money for Users. It acts as a wallet from where spends occur. In this section, Developer will find APIs related to CRUD operations of Accounts.
 */
export class Client {
  constructor(private readonly options: Client.Options) {}

  public async createAccount(
    request: HappayApi.CreateAccountRequest
  ): Promise<HappayApi.account.createAccount.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, "/account/"),
      method: "POST",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.auth?.token)),
      },
      body: serializers.CreateAccountRequest.json(request),
    });
    if (response.ok) {
      return {
        ok: true,
        body: serializers.CreateAccountResponse.parse(response.body as serializers.CreateAccountResponse.Raw),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }
}
