/**
 * This file auto-generated by Fern from our API Definition.
 */

import { HappayApi } from "../../..";
import * as core from "../../../core";

export type Response = core.APIResponse<HappayApi.CreateAccountResponse, HappayApi.account.createAccount.Error>;
export type Error = HappayApi.account.createAccount.Error._Unknown;

export declare namespace Error {
  interface _Unknown extends _Utils {
    errorName: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: HappayApi.account.createAccount.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    _other: (value: core.Fetcher.Error) => _Result;
  }
}
