/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface CreateAccountResponse {
  /**
   * unique reference of this account
   * eg: acc_db7ca20c268045f6bcdb27af064c19c4
   *
   */
  accountId: string;
  /**
   * unique reference of the user
   * eg: usr_5a33fa01ce4b4113a11ceb5c17c601c5
   *
   */
  userId: string;
}
