/**
 * This file auto-generated by Fern from our API Definition.
 */

import { HappayApi } from "../../..";

export interface CreateAccountRequest {
  accountType: HappayApi.AccountTypes;
  /** eg: usr_5a33fa01ce4b4113a11ceb5c17c601c5 */
  userId: string;
}
