/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as AccountClient } from "./resources/account/client/Client";

export declare namespace HappayApiClient {
  interface Options {
    environment?: environments.Environment | string;
    auth?: {
      token?: core.Supplier<core.BearerToken>;
    };
  }
}

export class HappayApiClient {
  constructor(private readonly options: HappayApiClient.Options) {}

  #account: AccountClient | undefined;

  public get account(): AccountClient {
    return (this.#account ??= new AccountClient(this.options));
  }
}
