/**
 * This file auto-generated by Fern from our API Definition.
 */

export const Environment = {
  /**
   * Base URL for UAT
   */
  Production: "https://api.uat-isac.happay.in",
  /**
   * Base URL for PRODUCTION
   */
  Sandbox: "https://api.isac.happay.in",
} as const;

export type Environment = typeof Environment.Production | typeof Environment.Sandbox;
